sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
      - avishayalon@gmail.com
env:
  global:
    - GH_USER_NAME="travis-ci"
    - GH_USER_EMAIL="travis@travis-ci.org"
    - AWS_DEFAULT_REGION=us-west-2
before_install:
- pip install --user awscli
install:
  - git clone -b ${CLONE_BRANCH} ${CLONE_URL} ${TRAVIS_BUILD_DIR}/../ros_app
  - cp -R ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_DIR}/../.ros_ci
  - mv ${TRAVIS_BUILD_DIR}/../ros_app ${TRAVIS_BUILD_DIR}
  - mv ${TRAVIS_BUILD_DIR}/../.ros_ci ${TRAVIS_BUILD_DIR}/ros_app/.ros_ci
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}/ros_app
  - cd ${TRAVIS_BUILD_DIR}
before_deploy:
# Skip querying of S3
- sed -i 's/.*aws s3 ls.*//g' .ros_ci/before_deploy.sh
- . .ros_ci/before_deploy.sh && set +e
jobs:
  include:
    - stage: Build & Bundle ROS1 Sample App
      env: 
        - ROS_VERSION=1
        - ROS_DISTRO=melodic
        - GAZEBO_VERSION=9
        - WORKSPACES="robot_ws simulation_ws"
        - SA_NAME=hello-world
        - SA_PACKAGE_NAME=hello_world_robot
        - NO_TEST=true
        - CLONE_URL=https://github.com/aws-robotics/aws-robomaker-sample-application-helloworld
        - CLONE_BRANCH=ros1
      script:
        - . .ros_ci/add_tag.sh && set +e
        - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - ".ros_ci/ce_build.sh"
        - kill %1
      deploy:
        - provider: script
          script: "Performing mock deploy stage"
          on:
            branch: master
            
    - stage: Build & Bundle ROS2 Sample App
      env: 
        - ROS_VERSION=2 
        - ROS_DISTRO=dashing
        - GAZEBO_VERSION=9
        - WORKSPACES="robot_ws simulation_ws"
        - SA_NAME=hello-world
        - SA_PACKAGE_NAME=hello_world_robot
        - NO_TEST=true
        - CLONE_URL=https://github.com/aws-robotics/aws-robomaker-sample-application-helloworld
        - CLONE_BRANCH=ros2
      script:
        - . .ros_ci/add_tag.sh && set +e
        - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - ".ros_ci/ce_build.sh"
        - kill %1
      deploy:
        - provider: script
          script: "Performing mock deploy stage"
          on:
            branch: master

    - stage: Build ROS1 Cloud Extension
      env:
        - PACKAGE_NAMES=aws_ros1_common
        - ROS_VERSION=1
        - ROS_DISTRO=kinetic
        - CLONE_URL=https://github.com/aws-robotics/utils-ros1
        - CLONE_BRANCH=master
      script:
        - ".ros_ci/ce_build.sh"
      before_deploy: # Blank override - no deploy stage for CEs
      after_deploy: # Blank override - no deploy stage for CEs
      
    - stage: Build ROS2 Cloud Extension
      env:
        - PACKAGE_NAMES=aws_ros2_common
        - ROS_VERSION=2
        - ROS_DISTRO=dashing
        - CLONE_URL="https://github.com/aws-robotics/utils-ros2" 
        - CLONE_BRANCH=master
      script:
        - ".ros_ci/ce_build.sh"
      before_deploy: # Blank override - no deploy stage for CEs
      after_deploy: # Blank override - no deploy stage for CEs
      
after_deploy:
- .ros_ci/post_deploy.sh
